apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: webapp-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nishchay18/devops:new_version
        ports:
        - containerPort: 8000
  strategy:
    canary:
      steps:
        - setWeight: 10
          pause:
            duration: 60s
