apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: webapp-rollout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: nishchay18/devops:v2  # Update this with your new image version
          ports:
            - containerPort: 8000
  strategy:
    canary:
      steps:
        - pause: {}
        - setWeight: 25
          pause:
            duration: 10s
        - setWeight: 50
          pause:
            duration: 10s
        - setWeight: 100
  selector:
    matchLabels:
      app: webapp
